-- MySQL Script generated by MySQL Workbench
-- 12/30/18 11:06:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Yugi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Yugi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Yugi` DEFAULT CHARACTER SET utf8 ;
USE `Yugi` ;

-- -----------------------------------------------------
-- Table `Yugi`.`Jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yugi`.`Jugador` (
  `cod_jug` INT(3) NOT NULL,
  `nombre_usuario` VARCHAR(25) NULL,
  `tipo_usuario` VARCHAR(25) NULL,
  `nombre_real` VARCHAR(25) NULL,
  `email` VARCHAR(25) NULL,
  PRIMARY KEY (`cod_jug`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yugi`.`tipo_carta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yugi`.`tipo_carta` (
  `idtipo_carta` INT NOT NULL AUTO_INCREMENT,
  `tipo_nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo_carta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yugi`.`Carta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yugi`.`Carta` (
  `cod_car` INT(3) NOT NULL,
  `nombre_carta` VARCHAR(20) NOT NULL,
  `poder_ataque` INT(8) NULL,
  `poder_def` INT(8) NULL,
  `tipo_carta_idtipo_carta` INT NOT NULL,
  PRIMARY KEY (`cod_car`),
  INDEX `fk_Carta_tipo_carta1_idx` (`tipo_carta_idtipo_carta` ASC),
  CONSTRAINT `fk_Carta_tipo_carta1`
    FOREIGN KEY (`tipo_carta_idtipo_carta`)
    REFERENCES `Yugi`.`tipo_carta` (`idtipo_carta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yugi`.`tipo_arena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yugi`.`tipo_arena` (
  `idtipo_arena` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_arena` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo_arena`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yugi`.`Arena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yugi`.`Arena` (
  `cod_are` INT(3) NOT NULL,
  `nombre_arena` VARCHAR(20) NULL,
  `r_min` INT(3) NULL,
  `r_max` INT(3) NULL,
  `tipo_arena_idtipo_arena` INT NOT NULL,
  PRIMARY KEY (`cod_are`),
  INDEX `fk_Arena_tipo_arena1_idx` (`tipo_arena_idtipo_arena` ASC),
  CONSTRAINT `fk_Arena_tipo_arena1`
    FOREIGN KEY (`tipo_arena_idtipo_arena`)
    REFERENCES `Yugi`.`tipo_arena` (`idtipo_arena`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yugi`.`Mazo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yugi`.`Mazo` (
  `cod_maz` INT(3) NOT NULL,
  `cod_jug` INT(3) NULL,
  PRIMARY KEY (`cod_maz`),
  INDEX `cod_jug_idx` (`cod_jug` ASC),
  CONSTRAINT `cod_jug`
    FOREIGN KEY (`cod_jug`)
    REFERENCES `Yugi`.`Jugador` (`cod_jug`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yugi`.`Partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yugi`.`Partida` (
  `Fecha` DATE NOT NULL,
  `Arena_cod_are` INT(3) NOT NULL,
  `Jugador_cod_jug` INT(3) NOT NULL,
  INDEX `fk_Partida_Arena1_idx` (`Arena_cod_are` ASC),
  INDEX `fk_Partida_Jugador1_idx` (`Jugador_cod_jug` ASC),
  CONSTRAINT `fk_Partida_Arena1`
    FOREIGN KEY (`Arena_cod_are`)
    REFERENCES `Yugi`.`Arena` (`cod_are`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partida_Jugador1`
    FOREIGN KEY (`Jugador_cod_jug`)
    REFERENCES `Yugi`.`Jugador` (`cod_jug`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yugi`.`Tipo_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yugi`.`Tipo_Usuario` (
  `Cod_tipo` INT NOT NULL,
  `nombre_tipo` VARCHAR(25) NULL,
  PRIMARY KEY (`Cod_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yugi`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yugi`.`Usuario` (
  `Cod_Usu` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(25) NULL,
  `contraseña` VARCHAR(25) NULL,
  `Jugador_cod_jug` INT(3) NOT NULL,
  `Tipo_Usuario_Cod_tipo` INT NOT NULL,
  PRIMARY KEY (`Cod_Usu`),
  INDEX `fk_Usuario_Jugador1_idx` (`Jugador_cod_jug` ASC),
  INDEX `fk_Usuario_Tipo_Usuario1_idx` (`Tipo_Usuario_Cod_tipo` ASC),
  CONSTRAINT `fk_Usuario_Jugador1`
    FOREIGN KEY (`Jugador_cod_jug`)
    REFERENCES `Yugi`.`Jugador` (`cod_jug`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Tipo_Usuario1`
    FOREIGN KEY (`Tipo_Usuario_Cod_tipo`)
    REFERENCES `Yugi`.`Tipo_Usuario` (`Cod_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yugi`.`Asugnacion_Mazo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yugi`.`Asugnacion_Mazo` (
  `idAsugnacion_Mazo` INT NOT NULL AUTO_INCREMENT,
  `Mazo_cod_maz` INT(3) NOT NULL,
  `Carta_cod_car` INT(3) NOT NULL,
  PRIMARY KEY (`idAsugnacion_Mazo`),
  INDEX `fk_Asugnacion_Mazo_Mazo1_idx` (`Mazo_cod_maz` ASC),
  INDEX `fk_Asugnacion_Mazo_Carta1_idx` (`Carta_cod_car` ASC),
  CONSTRAINT `fk_Asugnacion_Mazo_Mazo1`
    FOREIGN KEY (`Mazo_cod_maz`)
    REFERENCES `Yugi`.`Mazo` (`cod_maz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asugnacion_Mazo_Carta1`
    FOREIGN KEY (`Carta_cod_car`)
    REFERENCES `Yugi`.`Carta` (`cod_car`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yugi`.`Niveles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yugi`.`Niveles` (
  `idRanking` INT NOT NULL,
  `nombre_nivel` VARCHAR(45) NULL,
  PRIMARY KEY (`idRanking`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yugi`.`Copas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yugi`.`Copas` (
  `idCopas` INT NOT NULL,
  `cantidad_copas` INT NULL,
  `Jugador_cod_jug` INT(3) NOT NULL,
  PRIMARY KEY (`idCopas`),
  INDEX `fk_Copas_Jugador1_idx` (`Jugador_cod_jug` ASC),
  CONSTRAINT `fk_Copas_Jugador1`
    FOREIGN KEY (`Jugador_cod_jug`)
    REFERENCES `Yugi`.`Jugador` (`cod_jug`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yugi`.`Ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yugi`.`Ranking` (
  `idRanking` INT NOT NULL AUTO_INCREMENT,
  `Jugador_cod_jug` INT(3) NOT NULL,
  `Niveles_idRanking` INT NOT NULL,
  PRIMARY KEY (`idRanking`),
  INDEX `fk_Ranking_Jugador1_idx` (`Jugador_cod_jug` ASC),
  INDEX `fk_Ranking_Niveles1_idx` (`Niveles_idRanking` ASC),
  CONSTRAINT `fk_Ranking_Jugador1`
    FOREIGN KEY (`Jugador_cod_jug`)
    REFERENCES `Yugi`.`Jugador` (`cod_jug`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ranking_Niveles1`
    FOREIGN KEY (`Niveles_idRanking`)
    REFERENCES `Yugi`.`Niveles` (`idRanking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
