-- MySQL Script generated by MySQL Workbench
-- 12/14/18 00:42:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Yugi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Yugi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Yugi` DEFAULT CHARACTER SET utf8 ;
USE `Yugi` ;

-- -----------------------------------------------------
-- Table `Yugi`.`Arena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yugi`.`Arena` (
  `cod_are` INT(3) NOT NULL,
  `nombre_arena` VARCHAR(20) NULL,
  `tipo_arena` VARCHAR(20) NULL,
  `r_min` INT(3) NULL,
  `r_max` INT(3) NULL,
  PRIMARY KEY (`cod_are`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yugi`.`Jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yugi`.`Jugador` (
  `cod_jug` INT(3) NOT NULL,
  `nombre_usuario` VARCHAR(25) NULL,
  `tipo_usuario` VARCHAR(25) NULL,
  `nombre_real` VARCHAR(25) NULL,
  `email` VARCHAR(25) NULL,
  `ranking` INT(3) NOT NULL,
  `cod_are` INT(3) NULL,
  PRIMARY KEY (`cod_jug`),
  INDEX `cod_are_idx` (`cod_are` ASC),
  CONSTRAINT `cod_are`
    FOREIGN KEY (`cod_are`)
    REFERENCES `Yugi`.`Arena` (`cod_are`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yugi`.`Carta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yugi`.`Carta` (
  `cod_car` INT(3) NOT NULL,
  `nombre_carta` VARCHAR(20) NOT NULL,
  `tipo_carta` VARCHAR(20) NULL,
  `poder_ataque` INT(8) NULL,
  `poder_def` INT(8) NULL,
  PRIMARY KEY (`cod_car`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yugi`.`Mazo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yugi`.`Mazo` (
  `cod_maz` INT(3) NOT NULL,
  `cod_car` INT(3) NULL,
  `cod_jug` INT(3) NULL,
  PRIMARY KEY (`cod_maz`),
  INDEX `cod_car_idx` (`cod_car` ASC),
  INDEX `cod_jug_idx` (`cod_jug` ASC),
  CONSTRAINT `cod_car`
    FOREIGN KEY (`cod_car`)
    REFERENCES `Yugi`.`Carta` (`cod_car`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_jug`
    FOREIGN KEY (`cod_jug`)
    REFERENCES `Yugi`.`Jugador` (`cod_jug`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
